// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4gBqWKz9_gsAkmi69JcwOn4WMBB_SDVI',
    appId: '1:325231099194:web:4e6f83cd9fb6fe10982403',
    messagingSenderId: '325231099194',
    projectId: 'test-firebase-notification-0at',
    authDomain: 'test-firebase-notification-0at.firebaseapp.com',
    storageBucket: 'test-firebase-notification-0at.appspot.com',
    measurementId: 'G-MY8DG1WYHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPtfdLMReh-uHPv9TIp-0RJCOK50XAgw8',
    appId: '1:325231099194:android:3ed21b547b42a800982403',
    messagingSenderId: '325231099194',
    projectId: 'test-firebase-notification-0at',
    storageBucket: 'test-firebase-notification-0at.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB55SnnyXUGbRaVZiEC0nuCmTXy_wVyZB8',
    appId: '1:325231099194:ios:0fed9b97382ac600982403',
    messagingSenderId: '325231099194',
    projectId: 'test-firebase-notification-0at',
    storageBucket: 'test-firebase-notification-0at.appspot.com',
    iosBundleId: 'com.example.firebaseNotification1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB55SnnyXUGbRaVZiEC0nuCmTXy_wVyZB8',
    appId: '1:325231099194:ios:0fed9b97382ac600982403',
    messagingSenderId: '325231099194',
    projectId: 'test-firebase-notification-0at',
    storageBucket: 'test-firebase-notification-0at.appspot.com',
    iosBundleId: 'com.example.firebaseNotification1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4gBqWKz9_gsAkmi69JcwOn4WMBB_SDVI',
    appId: '1:325231099194:web:f96f9e51b002c56a982403',
    messagingSenderId: '325231099194',
    projectId: 'test-firebase-notification-0at',
    authDomain: 'test-firebase-notification-0at.firebaseapp.com',
    storageBucket: 'test-firebase-notification-0at.appspot.com',
    measurementId: 'G-7CJT3TTWX5',
  );
}
